- alias: AC weekday (heat 18)
  trigger:
  - platform: time
    minutes: /5
    seconds: 0
  - platform: state
    entity_id: group.tracking
    to: not_home
    from: home
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.tracking
      state: not_home
    - condition: time
      after: 07:15:00
      before: '15:00:00'
      weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.mjovik
      temperature: 18
      operation_mode: Hot
  - service: climate.set_fan_mode
    data:
      fan_mode: Auto
- alias: AC weekday morning (heat 23)
  trigger:
    platform: time
    at: '5:50:00'
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: climate.set_temperature
    data:
      temperature: 23
      operation_mode: Hot
  - service: climate.set_fan_mode
    data:
      fan_mode: Auto
- alias: AC weekday afternoon (heat 23)
  trigger:
    platform: time
    at: '15:00:00'
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: climate.set_temperature
    data:
      temperature: 23
      operation_mode: Hot
  - service: climate.set_fan_mode
    data:
      fan_mode: Auto
- alias: Sleep
  trigger:
    platform: time
    at: '22:30:00'
  condition:
    condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
    service: script.goodnight
- alias: 'Patio door opened'
  # https://community.home-assistant.io/t/time-since-a-sensor-last-updated-in-a-condition/14503/5
  trigger:
    - platform: state
      entity_id: binary_sensor.altandorren
      to: 'on'
  condition:
    condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.patio_door_opened.attributes.last_triggered) | int > 10 }}'
  action:
    service: notify.notify
    data:
      message: "Patio door opened 10s ago."
