- id: 32e9a04e7a5b428885c5f42f50fe9db4
  alias: AC weekday (heat 18)
  trigger:
  - platform: time
    minutes: /5
    seconds: 0
  - platform: state
    entity_id: group.tracking
    to: not_home
    from: home
  condition:
  - condition: state
    entity_id: group.tracking
    state: not_home
  - condition: time
    after: 07:15:00
    before: '15:00:00'
  - condition: state
    entity_id: input_boolean.auto_ac
    state: 'on'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.trip_mode
    state: 'off'
  action:
  - service: climate.set_fan_mode
    data:
      entity_id: climate.mjovik
      fan_mode: Auto
  - service: climate.set_temperature
    data:
      entity_id: climate.mjovik
      temperature: 18
      operation_mode: heat
- id: 2b8a666493414996b86d91bfb82f7a63
  alias: AC weekday morning (heat 23)
  trigger:
  - at: '5:50:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.auto_ac
    state: 'on'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.trip_mode
    state: 'off'
  action:
  - data:
      entity_id: climate.mjovik
      fan_mode: Auto
    service: climate.set_fan_mode
  - data:
      entity_id: climate.mjovik
      operation_mode: heat
      temperature: 23
    service: climate.set_temperature
- id: 6c7d7b4527c243ada790a57ff40abada
  alias: AC weekday afternoon (heat 22)
  trigger:
  - at: '15:30:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.auto_ac
    state: 'on'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.trip_mode
    state: 'off'
  action:
  - data:
      entity_id: climate.mjovik
      fan_mode: Auto
    service: climate.set_fan_mode
  - data:
      entity_id: climate.mjovik
      operation_mode: heat
      temperature: 22
    service: climate.set_temperature
- id: 73d5ba997ef54e3287519482183ff550
  alias: Sleep
  trigger:
  - at: '22:30:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_tomorrow
    state: 'off'
  action:
  - service: script.goodnight
- id: ea98115788cd4f0db6aad83c2a3c8f98
  alias: Patio door opened
  trigger:
  - platform: state
    entity_id: binary_sensor.altandorren
    to: 'on'
  condition:
    condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.patio_door_opened.attributes.last_triggered)
      | int > 10 }}'
  action:
    service: notify.notify
    data:
      message: Patio door opened 10s ago.
- id: '1532938767682'
  alias: Turn off "stereo" when TV is off
  trigger:
  - entity_id: media_player.lg_webos_smart_tv
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: switch.stereo
    service: switch.turn_off
- id: '1534411228039'
  alias: Automatic "Vi är lediga" (on)
  trigger:
  - platform: template
    value_template: '{{ is_state("binary_sensor.workday_sensor", "off") or is_state("calendar.lediga",
      "on")}} '
  condition: []
  action:
  - alias: ''
    data:
      entity_id: input_boolean.vacation_mode
    service: input_boolean.turn_on
- id: '1534411228139'
  alias: Automatic "Vi är lediga" (off)
  trigger:
  - platform: template
    value_template: '{{ is_state("binary_sensor.workday_sensor", "on") and is_state("calendar.lediga",
      "off")}} '
  condition: []
  action:
  - alias: ''
    data:
      entity_id: input_boolean.vacation_mode
    service: input_boolean.turn_off
- id: '23'
  alias: Trip temp low (ac-heat)
  trigger:
  - minutes: /10
    platform: time
    seconds: 2
  condition:
  - condition: template
    value_template: '{{ states.sensor.vit_inne_temperature.state|int < states.input_number.trip_temp_low.state|int
      }}'
  - condition: state
    entity_id: input_boolean.trip_mode
    state: 'on'
  action:
  - data:
      fan_mode: Auto
    service: climate.set_fan_mode
  - data:
      entity_id: climate.mjovik
      operation_mode: heat
      temperature: '{{ states.input_number.trip_temp_low.state|int + 2 }}'
    service: climate.set_temperature
- id: '231'
  alias: Trip temp high (ac-cool)
  trigger:
  - minutes: /10
    platform: time
    seconds: 2
  condition:
  - condition: template
    value_template: '{{ states.sensor.vit_inne_temperature.state|int > states.input_number.trip_temp_high.state|int
      }}'
  - condition: state
    entity_id: input_boolean.trip_mode
    state: 'on'
  action:
  - data:
      fan_mode: Auto
    service: climate.set_fan_mode
  - data:
      entity_id: climate.mjovik
      operation_mode: Cool
      temperature: '{{ states.input_number.trip_temp_low.state|int }}'
    service: climate.set_temperature
- id: '2312'
  alias: Trip temp OK (AC-off)
  trigger:
  - minutes: /10
    platform: time
    seconds: 2
  condition:
  - condition: template
    value_template: '{{ states.sensor.vit_inne_temperature.state|int > states.input_number.trip_temp_low.state|int
      + 5 }}'
  - condition: template
    value_template: '{{ states.sensor.vit_inne_temperature.state|int < states.input_number.trip_temp_high.state|int
      - 5 }}'
  - condition: state
    entity_id: input_boolean.trip_mode
    state: 'on'
  action:
  - data:
      entity_id: climate.mjovik
    service: climate.turn_off
- id: '1536927135503'
  alias: Wakeup (sovrum on)
  trigger:
  - at: 06:10
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - data:
      entity_id: switch.sovrummet
    service: switch.turn_on
- id: '1536927181084'
  alias: Sovrum off
  trigger:
  - at: 07:10
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.sovrummet
    service: switch.turn_off
- id: '1536927330832'
  alias: Glödlampan on
  trigger:
  - event: sunset
    platform: sun
  condition:
  - before: '22:00'
    condition: time
  action:
  - data:
      brightness_pct: 50
      entity_id: light.glodlampan
    service: light.turn_on
- id: '1536927424259'
  alias: Glödlampan off (weekday)
  trigger:
  - at: '22:10'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.vacation_tomorrow
    state: 'off'
  action:
  - data:
      entity_id: light.glodlampan
    service: light.turn_off
- id: '1536927507191'
  alias: Glödlampa off (weekend)
  trigger:
  - at: '23:30'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.vacation_tomorrow
    state: 'on'
  action:
  - data:
      entity_id: light.glodlampan
    service: light.turn_off
- id: '1542352771711'
  alias: Ljusslingor (on workday)
  trigger:
  - at: 06:00
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - delay: 00:{{ (range(20, 40)|random|int) }}:00
  - data:
      entity_id:
      - switch.ljusslingor
      - light.utebelysning
    service: switch.turn_on
