homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

  customize_glob:
    "*.*":
        custom_ui_state_card: state-card-custom-ui
    "light.*":
      assumed_state: false
    "switch.*":
      assumed_state: false
    "device_tracker.*":
      show_last_changed: true
      # hidden: true

  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  extra_html_url:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui.html
  extra_html_url_es5:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui-es5.html

# Enables configuration UI
config:

http:
  # Add the following modification: https://github.com/orobardet/dsm-reverse-proxy-websocket
  base_url: https://hass.erlandsson.myds.me
  api_password: !secret api_password
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
    - https://github.com
    - https://raw.githubusercontent.com
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.2
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24
    - 194.47.137.69

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
  #  - daikin

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

recorder:

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret asuswrt_user
    port: 22
    mode: router
    ssh_key: /config/ssh_key


tellduslive:
  host: 192.168.1.10

climate:
  - platform: daikin
    host: 192.168.1.15

daikin:
  hosts:
  - 192.168.1.15

# customizer:
#  custom_ui: local

# Track the sun
sun:

influxdb:
  host: 192.168.1.2
  database: hass
  default_measurement: state
  max_retries: 3
  tags_attributes:
    - friendly_name
    - hidden
  exclude:
    domains:
      - automation
      - group

sensor:
  #https://home-assistant.io/components/sensor.template/
  - platform: template
    sensors:
      krypgrund_dew_point:
        unit_of_measurement: "%"
        value_template: "{{ ((states.sensor.krypgrund_temperature.state | float * 1) -
          ((100 - (states.sensor.krypgrund_humidity.state | float * 1)) / 5)) | round(2) }}"
      uptime:
        value_template: >-
          {{ (as_timestamp(now()) - as_timestamp(states.sensor.sparsnas_energy_consumption_momentary.last_updated)) < 600 }}
      hemma:
        value_template: >-
          {% if is_state("device_tracker.78f882cf23d5", "home") or
          is_state("device_tracker.ac3743a16232", "home") -%}
          Someone is home
          {%- else -%}
          No one is home
          {%- endif %}
      dark_sky:
        entity_picture_template: "{{states.sensor.dark_sky_summary.attributes.entity_picture}}"
        value_template: "{{states.sensor.dark_sky_temperature.state}}"
        friendly_name: "Dark Sky"
        friendly_name_template: "{{states.sensor.dark_sky_summary.state}} — ⟨Dark Sky⟩"
        unit_of_measurement: "°C"
      daikin_indoor:
        value_template: "{{ states.sensor.inside_temperature_mjovik_inside_temperature.state }}"
      daikin_outdoor:
        value_template: "{{ states.sensor.outside_temperature_mjovik_outside_temperature.state }}"
  - platform: sonarr
    api_key: !secret sonarr_api_key
    host: 192.168.1.2
    days: 3
  #- platform: snmp
  #  name: "Wan in"
  #  host: 192.168.1.1
  #  baseoid: 1.3.6.1.2.1.2.2.1.10.4
  #  accept_errors: true
  #  unit_of_measurement: kB
  #  value_template: '{{((value | int) / 1024) | int}}'
  #- platform: snmp
  #  name: "Wan out"
  #  host: 192.168.1.1
  #  baseoid: 1.3.6.1.2.1.2.2.1.16.4
  #  accept_errors: true
  #  unit_of_measurement: kB
  #  value_template: '{{((value | int) / 1024) | int}}'
  - platform: darksky #https://pastebin.com/iX7u4ZSg
    api_key: !secret darksky_api_key
    update_interval: '00:03'
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - temperature
      - apparent_temperature
      - precip_probability
      - wind_speed
      - pressure
      - wind_bearing
      - humidity
      - cloud_cover
      - dew_point
      - hourly_summary
      - daily_summary
  - platform: rest
    resource: https://api.ioe.allbin.se/buoys
    name: Badtemp Tallholmen
    unit_of_measurement: °C
    value_template: '{{ value_json|selectattr("name", "equalto", "Tallholmen")|map(attribute="temperature")|first|round(1) }}'

binary_sensor:
  - platform: workday
    country: SE

google:
  client_id:     !secret google_client_id
  client_secret: !secret google_client_secret

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: home

input_boolean:
  vacation_mode:
    name: Vi är lediga
    icon: mdi:bell-sleep
  trip_mode:
    name: Vi är på turné
    icon: mdi:tent
  auto_ac:
    name: Automatic AC
    icon: mdi:air-conditioner

input_number:
  trip_temp_low:
    name: Lägsta temp
    unit_of_measurement: °C
    min: 5
    max: 25
    step: 1
    icon: mdi:thermometer
  trip_temp_high:
    name: Högsta temp
    unit_of_measurement: °C
    min: 15
    max: 35
    step: 1
    icon: mdi:thermometer

history_graph:
  #gr1:
  #  name: Temperature 5 days
  #  hours_to_show: 120
  #  refresh: 60
  #  entities:
  #    - sensor.vit_inne_temperature
  #    - sensor.krypgrund_temperature
  #    - sensor.ute_temperature
  #    - sensor.daikin_outdoor
  #gr2:
  #  name: Temperature 10 days
  #  hours_to_show: 240
  #  refresh: 60
  #  entities:
  #    - sensor.vit_inne_temperature
  #    - sensor.krypgrund_temperature
  #    - sensor.ute_temperature
  #    - sensor.daikin_outdoor
  #gr3:
  #  name: Temperature 30 days
  #  hours_to_show: 720
  #  refresh: 60
  #  entities:
  #    - sensor.vit_inne_temperature
  #    - sensor.krypgrund_temperature
  #    - sensor.ute_temperature
  #    - sensor.daikin_outdoor
  #gr4:
  #  name: Temperature year
  #  hours_to_show: 8760
  #  refresh: 60
  #  entities:
  #    - sensor.vit_inne_temperature
  #    - sensor.krypgrund_temperature
  #    - sensor.ute_temperature
  #    - sensor.daikin_outdoor

# Text to speech
tts:
  - platform: google

cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


media_player:
  - platform: plex
  - platform: webostv
    host: 192.168.1.12
  - platform: spotify
    client_id: c972de83eee94413874f25f479e6a5d3
    client_secret: da26ea3d832a4881bd72639bb2f0d39c


logger:
  # default: warning
  default: error
  logs:
    #netdisco: debug
    #requests: debug
    #tellduslive: debug
    lg_webos_smart_tv: info
    #daikin: debug
    asuswrt: debug
    device_tracker: debug
    homeassistant.components.sensor.rest: critical

#https://community.home-assistant.io/t/spotify-playlist-player/2249
#https://github.com/Aksinder/Home-Assistant1

#https://gist.github.com/randellhodges/96a0cd9bafa03fb90ada49040d65f1b0
#group_globber:
#  groups:
#    group.devices:
#      - device_tracker.*
