homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

  customize_glob:
    "device_tracker.*":
      show_last_changed: true
      # hidden: true

  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 192.168.1.0/24
        - 194.47.137.69

default_config:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

http:
  # Add the following modification: https://github.com/orobardet/dsm-reverse-proxy-websocket
  server_port: 8124
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.2

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true


# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.sonarr_upcoming_media
      - sensor.plex_recently_added
      - sensor.time
      - sensor.time_date
    domains:
      - sun

recorder:
  auto_purge: true
  purge_keep_days: 14
  exclude:
    entities:
      - sensor.sonarr_upcoming_media
      - sensor.plex_recently_added
      - sensor.time
      - sensor.time_date
      - sensor.date_time
      - sensor.date
      - sensor.ambient_light
      - sensor.ambient_light_10
      - sensor.fonster_vardagsrum_power
      - sensor.washer_runtime
      - sensor.sparsnas_frequency_error
    domains:
      - weather

notify:
  - platform: pushover
    name: pushover
    api_key: !secret pushover_api
    user_key: !secret pushover_user
  - platform: html5
    name: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_priv_key
    vapid_email: !secret fredrik_gravatar

asuswrt:
  host: 192.168.1.1
  username: !secret asuswrt_user
  port: 22
  ssh_key: /config/ssh_key

# tellduslive:
#  host: 192.168.1.10

point:
  client_id:     !secret point_id
  client_secret: !secret point_secret

influxdb:
  host: 192.168.1.2
  database: hass
  default_measurement: state
  max_retries: 3
  tags_attributes:
    - friendly_name
    - hidden
  exclude:
    domains:
      - automation
      - group

rss_feed_template:
  uptime:
    requires_api_password: false
    title: "Uptime"
    items:
    - title: 'Sparsnäs'
      description: >-
        Sparsnäs is {{ 'up' if states('sensor.sparsnas_w') != 'unknown' and (now() - states.sensor.sparsnas_w.last_updated).seconds < 600 else 'down' }}

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
  # https://home-assistant.io/components/sensor.template/
  - platform: template
    sensors:
      krypgrund_dew_point:
        friendly_name: Krypgrund Daggpunkt
        unit_of_measurement: "°C"
        value_template: "{{ ((states('sensor.krypgrund_temperature') | float * 1) -
          ((100 - (states('sensor.krypgrund_humidity') | float * 1)) / 5)) | round(2) }}"
        device_class: temperature
      hemma:
        value_template: >-
          {% if is_state("device_tracker.78f882cf23d5", "home") or
          is_state("device_tracker.ac3743a16232", "home") -%}
          Someone is home
          {%- else -%}
          No one is home
          {%- endif %}
      daikin_target:
        value_template: "{{ states.climate.mjovik.attributes.temperature }}"
        unit_of_measurement: "°C"
        friendly_name: "AC target temperature"
        device_class: temperature
      daikin_status:
        value_template: "{{ states('climate.mjovik') }}"
        unit_of_measurement: "AC State"
        friendly_name: "AC State"
      skollunch:
        value_template: "{{ states.calendar.skolmaten_nattrabyskolan.attributes.message }}"
        friendly_name: "Skollunch Nättabyskolan"
        icon_template: mdi:silverware-variant
        unit_of_measurement: ""

binary_sensor:
  - platform: workday
    country: SE
  - platform: workday
    country: SE
    days_offset: 1
    name: workday_tomorrow

google:
  client_id:     !secret google_client_id
  client_secret: !secret google_client_secret

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: home

input_boolean:
  vacation_mode:
    name: Vi är lediga
    icon: mdi:bell-sleep
  vacation_tomorrow:
    name: Vi är lediga imorgon
  trip_mode:
    name: Vi är på turné
    icon: mdi:tent
  auto_ac:
    name: Automatic AC
    icon: mdi:air-conditioner

input_number:
  trip_temp_low:
    name: Lägsta temp
    unit_of_measurement: °C
    min: 5
    max: 25
    step: 1
    icon: mdi:thermometer
  trip_temp_high:
    name: Högsta temp
    unit_of_measurement: °C
    min: 15
    max: 35
    step: 1
    icon: mdi:thermometer

# Text to speech
# tts:
#  - platform: google_translate
#    service_name: google_say

# cloud:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

wake_on_lan:

webostv:
  host: 192.168.1.12
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: a0-6f-aa-48-ed-64

spotify:
  client_id:     !secret spotify_id
  client_secret: !secret spotify_secret

    
logger: !include logger.yaml

#https://community.home-assistant.io/t/spotify-playlist-player/2249
#https://github.com/Aksinder/Home-Assistant1


shelly:


shell_command:
  restart_mqtt: curl --unix-socket /var/run/docker.sock -X POST http:/v1.39/containers/da7172d8590b/restart

