
android2c3c68e2b6856433:
  hide_if_away: false
  mac: 2C:59:8A:70:70:82
  name: Nexus 5X (Fredrik)
  picture: !secret fredrik_picture
  track: true
  vendor: LG Electronics (Mobile Communications)

78f882cf23d5:
  hide_if_away: false
  icon: mdi:cellphone-android
  mac: 78:F8:82:CF:23:D5
  name: Nexus 5X (Fredrik old)
  picture: !secret fredrik_picture
  track: true

ac3743a16232:
  hide_if_away: false
  icon: mdi:cellphone-android
  mac: AC:37:43:A1:62:32
  name: Johanna
  picture: !secret johanna_picture
  track: true
  vendor: HTC Corporation

f0c77fb3ffe2:
  hide_if_away: true
  icon: mdi:air-conditioner
  mac: F0:C7:7F:B3:FF:E2
  name: Sensibo
  picture:
  track: false
  vendor: unknown

784f43754df9:
  hide_if_away: false
  icon: mdi:laptop-mac
  mac: 78:4F:43:75:4D:F9
  name: FredriksMBP2017
  picture:
  track: true
  vendor: unknown

a06faa48ed64:
  hide_if_away: false
  icon: mdi:television
  mac: A0:6F:AA:48:ED:64
  name: TV
  picture:
  track: true
  vendor: unknown

6cadf84ab3a0:
  hide_if_away: false
  icon: mdi:cast
  mac: 6C:AD:F8:4A:B3:A0
  name: Chromecast Living room
  picture:
  track: true
  vendor: AzureWave Technology Inc.

9cf387c11dd2:
  hide_if_away: false
  icon: mdi:tablet-ipad
  mac: 9C:F3:87:C1:1D:D2
  name: 9cf387c11dd2
  picture:
  track: true
  vendor: unknown

3412986c3e80:
  hide_if_away: false
  icon: mdi:tablet-ipad
  mac: 34:12:98:6C:3E:80
  name: Golden iPad
  picture:
  track: true
  vendor: Apple Inc.

00044b55d114:
  hide_if_away: false
  icon: mdi:cast
  mac: 00:04:4B:55:D1:14
  name: Nvidia Sheild
  picture:
  track: true
  vendor: NVIDIA

141aa3d4c5af:
  hide_if_away: false
  icon:
  mac: 14:1A:A3:D4:C5:AF
  name: 141aa3d4c5af-unknown :/
  picture:
  track: true
  vendor: Motorola Mobility LLC, a Lenovo Company

e8b1fc93b7f0:
  hide_if_away: false
  icon: mdi:laptop-windows
  mac: E8:B1:FC:93:B7:F0
  name: Johanna work
  picture:
  track: true
  vendor: unknown

a408eaf07afe:
  hide_if_away: false
  icon: mdi:air-conditioner
  mac: A4:08:EA:F0:7A:FE
  name: Daikin
  picture:
  track: true
  vendor: Murata Manufacturing Co., Ltd.

00113261ee4e:
  hide_if_away: false
  icon: mdi:server-network
  mac: 00:11:32:61:EE:4E
  name: Synology
  picture:
  track: true
  vendor: unknown

bcf685760256:
  hide_if_away: false
  icon:
  mac: BC:F6:85:76:02:56
  name: bcf685760256
  picture: D-Link
  track: false
  vendor: unknown

tellstickznetlite:
  hide_if_away: false
  icon:
  mac: AC:CA:54:01:B5:EA
  name: TellStick-ZNet-Lite
  picture:
  track: true
  vendor: unknown

0008ae922b20:
  hide_if_away: false
  icon:
  mac: 00:08:AE:92:2B:20
  name: 0008ae922b20
  picture:
  track: true
  vendor: unknown

iphonej:
  hide_if_away: false
  icon:
  mac: 30:F7:C5:E4:BF:97
  name: iPhone-J
  picture:
  track: true
  vendor: Apple, Inc.

macbook:
  hide_if_away: false
  icon:
  mac: 8C:85:90:62:FE:84
  name: MacBook
  picture:
  track: true
  vendor: Apple, Inc.

johannasmacbook:
  hide_if_away: false
  icon:
  mac: 00:0E:C6:E2:0D:50
  name: JohannasMacBook
  picture:
  track: true
  vendor: ASIX ELECTRONICS CORP.

wii:
  hide_if_away: false
  icon:
  mac: 00:1B:EA:CF:21:54
  name: Wii
  picture:
  track: true
  vendor: Nintendo Co., Ltd.

3052cbdf3ae1:
  hide_if_away: false
  icon:
  mac: 30:52:CB:DF:3A:E1
  name: 3052cbdf3ae1
  picture:
  track: true
  vendor: Liteon Technology Corporation

esp_1c2f10:
  hide_if_away: false
  icon:
  mac: A0:20:A6:1C:2F:10
  name: ESP 1C2F10
  picture:
  track: true
  vendor: Espressif Inc.

macbookpro:
  hide_if_away: false
  icon:
  mac: 00:26:BB:1A:DF:AA
  name: MacBook-Pro
  picture:
  track: true
  vendor: Apple, Inc.

androidb09c2197f29ffbd4:
  hide_if_away: false
  icon:
  mac: 48:5A:3F:6C:02:AB
  name: Jessicas telefon
  picture:
  track: true
  vendor: WISOL

moode:
  hide_if_away: false
  icon:
  mac: B8:27:EB:4E:E6:03
  name: moode
  picture:
  track: true
  vendor: Raspberry Pi Foundation

point:
  hide_if_away: false
  icon:
  mac: B0:F1:EC:1D:1B:70
  name: Point
  picture:
  track: true

esp_12125c:
  hide_if_away: false
  icon:
  mac: 5C:CF:7F:12:12:5C
  name: ESP 12125C
  picture:
  track: true

9c5cf9c2b173:
  hide_if_away: false
  icon:
  mac: 9C:5C:F9:C2:B1:73
  name: 9c5cf9c2b173
  picture:
  track: true

galaxys8:
  hide_if_away: false
  icon: mdi:cellphone-android
  mac: 24:18:1D:A9:93:3D
  name: Galaxy-S8
  picture:
  track: true

404e36221e29:
  hide_if_away: false
  mac: 40:4E:36:22:1E:29
  name: Fredrik's Pixel
  picture: !secret fredrik_picture
  track: true

14c913bb1982:
  hide_if_away: false
  icon:
  mac: 14:C9:13:BB:19:82
  name: 14c913bb1982
  picture:
  track: true

smartremote76b:
  hide_if_away: false
  icon: mdi:remote
  mac: 38:D7:CA:00:07:6B
  name: Sevenhugs Smart Remote
  picture:
  track: true

galaxya32016:
  hide_if_away: false
  icon:
  mac: 50:9E:A7:77:1A:FF
  name: Galaxy-A3-2016
  picture:
  track: true

24df6a33898c:
  hide_if_away: false
  icon:
  mac: 24:DF:6A:33:89:8C
  name: 24df6a33898c
  picture:
  track: true

loattasipad:
  hide_if_away: true
  icon: mdi:tablet-ipad
  mac: 08:E6:89:E5:A9:46
  name: Lottas-ipad
  picture:
  track: true

galaxynote9:
  hide_if_away: true
  icon:
  mac: 08:C5:E1:D7:F0:A9
  name: Galaxy-Note9 Lotta
  picture:
  track: true

leasipad:
  hide_if_away: false
  icon: mdi:tablet-ipad
  mac: 58:E6:BA:7D:AB:9B
  name: Leas-iPad
  picture:
  track: true

emmasipad:
  hide_if_away: false
  icon: mdi:tablet-ipad
  mac: 8C:FE:57:B2:BE:71
  name: Emmas-iPad
  picture:
  track: true

lennarts_ipad:
  hide_if_away: false
  icon:
  mac: 3C:15:C2:07:6B:00
  name: Lennarts-iPad
  picture:
  track: true

android_7c7d9f390472c18a:
  hide_if_away: false
  icon:
  mac: E0:A3:AC:76:7A:92
  name: android-7c7d9f390472c18a
  picture:
  track: true

ist_dev:
  hide_if_away: false
  icon:
  mac: B4:8B:19:84:7A:6A
  name: Ist-dev
  picture:
  track: true

ddsm1:
  hide_if_away: false
  icon:
  mac: 02:11:32:14:BF:A1
  name: DDSM1
  picture:
  track: true

96_1a_39_d3_68_9a:
  hide_if_away: false
  icon:
  mac: 96:1A:39:D3:68:9A
  name: 96 1a 39 d3 68 9a
  picture:
  track: true

galaxy_a8_2018:
  hide_if_away: false
  icon:
  mac: 58:B1:0F:B0:5F:EE
  name: Galaxy-A8-2018
  picture:
  track: true

rebeccas_iphone:
  hide_if_away: false
  icon:
  mac: 38:71:DE:7C:DA:D8
  name: Rebeccas-iPhone
  picture:
  track: true

test:
  hide_if_away: false
  icon:
  mac: 2C:3A:E8:35:9F:E7
  name: test
  picture:
  track: false

led_strip:
  hide_if_away: false
  icon:
  mac: 60:01:94:74:65:0D
  name: led strip
  picture:
  track: false

c6_49_03_aa_c9_e1:
  hide_if_away: false
  icon:
  mac: C6:49:03:AA:C9:E1
  name: c6 49 03 aa c9 e1
  picture:
  track: false

stolx0560:
  hide_if_away: false
  icon:
  mac: CC:2F:71:5C:CB:28
  name: Fredrik's STOLX0560
  picture:
  track: true

galaxy_a8_2018_2:
  hide_if_away: false
  icon:
  mac: A8:34:6A:60:FC:1A
  name: Fredrik's Galaxy-A8-2018
  picture:
  track: true

display_node:
  hide_if_away: false
  icon:
  mac: CC:50:E3:AF:87:A8
  name: display node
  picture:
  track: false

google_maps_joferlandsson_gmail_com:
  hide_if_away: false
  icon:
  mac:
  name: Fredrik @ google maps
  picture: !secret fredrik_picture
  track: true

google_maps_105279642947500708897:
  hide_if_away: false
  icon:
  mac:
  name: google maps 105279642947500708897
  picture: https://lh3.googleusercontent.com/a-/AAuE7mCtBLEpmoG8Rut3kjqc8yHb8kt1DY1an3AjV9DH7eo
  track: true

ella_iphone:
  hide_if_away: false
  icon:
  mac: 0C:51:01:1A:00:4D
  name: Ella--iPhone
  picture:
  track: true

ista_vccyv1zwbmtdk1330514:
  hide_if_away: false
  icon:
  mac: 00:10:02:42:40:08
  name: ISTA-VCCYV1ZWBMTDK1330514
  picture:
  track: true

volvo_krz81s:
  hide_if_away: false
  icon: mdi:car
  mac:
  name: KRZ81S
  picture:
  track: true

google_maps_104065646185363141038:
  hide_if_away: false
  icon:
  mac:
  name: google maps 104065646185363141038
  picture: https://lh6.googleusercontent.com/-MAKZ23O92Lw/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3req8k0W9-nbkyPEEfb-ip5QNtRQAQ/photo.jpg
  track: true

esp_ae8ea1:
  hide_if_away: false
  icon:
  mac: 5C:CF:7F:AE:8E:A1
  name: ESP AE8EA1
  picture:
  track: true

2e_87_ea_62_1f_21:
  hide_if_away: false
  icon:
  mac: 2E:87:EA:62:1F:21
  name: 2e 87 ea 62 1f 21
  picture:
  track: true

ae_07_7c_7f_3e_86:
  hide_if_away: false
  icon:
  mac: AE:07:7C:7F:3E:86
  name: ae 07 7c 7f 3e 86
  picture:
  track: true

shellydimmer_d0af99:
  hide_if_away: false
  icon:
  mac: 98:F4:AB:D0:AF:99
  name: shellydimmer-D0AF99
  picture:
  track: true

inv001000080371:
  hide_if_away: false
  icon:
  mac: 60:F2:62:F2:AF:EE
  name: INV001000080371
  picture:
  track: true

moode_2:
  icon:
  mac: A6:9E:53:3B:35:6F
  name: moode
  picture:
  track: true

moode_3:
  icon:
  mac: 52:25:56:BE:CF:C1
  name: moode
  picture:
  track: true

moode_4:
  icon:
  mac: 16:53:BA:C1:D8:B1
  name: moode
  picture:
  track: true

moode_5:
  icon:
  mac: C2:7E:42:30:41:34
  name: moode
  picture:
  track: true

moode_6:
  icon:
  mac: 6E:2F:F0:FE:39:8F
  name: moode
  picture:
  track: true

moode_7:
  icon:
  mac: EA:8B:D2:AB:8E:A3
  name: moode
  picture:
  track: true

moode_8:
  icon:
  mac: 1E:D6:41:A4:13:4C
  name: moode
  picture:
  track: true

3c_91_80_9a_72_65:
  icon:
  mac: 3C:91:80:9A:72:65
  name: 3c_91_80_9a_72_65
  picture:
  track: true

google_nest_hub:
  icon:
  mac: 7C:2E:BD:28:A9:6D
  name: Google-Nest-Hub
  picture:
  track: true

shellydimmer_d0ee05:
  icon:
  mac: 98:F4:AB:D0:EE:05
  name: shellydimmer-D0EE05
  picture:
  track: true

2a_2b_91_f3_42_82:
  icon:
  mac: 2A:2B:91:F3:42:82
  name: 2a_2b_91_f3_42_82
  picture:
  track: true

leia_s_ipad:
  icon:
  mac: 10:29:59:54:B2:67
  name: Leia-s-iPad
  picture:
  track: true

iphone:
  icon:
  mac: 7C:9A:1D:E1:6F:49
  name: iPhone
  picture:
  track: true

ac_37_43_50_72_fb:
  icon:
  mac: AC:37:43:50:72:FB
  name: ac_37_43_50_72_fb
  picture:
  track: true

iduns_ipad:
  icon:
  mac: 8C:FE:57:86:04:D9
  name: Iduns-iPad
  picture:
  track: true

vickys_ipad:
  icon:
  mac: F0:F6:1C:DB:B6:FC
  name: Vickys-iPad
  picture:
  track: true

macbook_air:
  icon:
  mac: 14:7D:DA:52:B4:28
  name: MacBook-Air
  picture:
  track: true

oneplus5t:
  icon:
  mac: 94:65:2D:41:DF:86
  name: OnePlus5T
  picture:
  track: true

00_13_d4_10_3b_37:
  icon:
  mac: 00:13:D4:10:3B:37
  name: 00_13_d4_10_3b_37
  picture:
  track: true

00_13_d4_10_3b_35:
  icon:
  mac: 00:13:D4:10:3B:35
  name: 00_13_d4_10_3b_35
  picture:
  track: true

46_19_46_d4_49_e4:
  icon:
  mac: 46:19:46:D4:49:E4
  name: 46_19_46_d4_49_e4
  picture:
  track: true

b2_f4_93_48_8d_ba:
  icon:
  mac: B2:F4:93:48:8D:BA
  name: b2_f4_93_48_8d_ba
  picture:
  track: true

e0_63_da_06_66_f7:
  icon:
  mac: E0:63:DA:06:66:F7
  name: e0_63_da_06_66_f7
  picture:
  track: true

macbook_pro:
  icon:
  mac: 14:7D:DA:7A:BD:1B
  name: MacBook-Pro
  picture:
  track: true

9e_26_cf_04_d1_77:
  icon:
  mac: 9E:26:CF:04:D1:77
  name: 9e_26_cf_04_d1_77
  picture:
  track: true

66_40_5b_b8_20_8b:
  icon:
  mac: 66:40:5B:B8:20:8B
  name: 66_40_5b_b8_20_8b
  picture:
  track: true

ae_19_82_10_08_ce:
  icon:
  mac: AE:19:82:10:08:CE
  name: ae_19_82_10_08_ce
  picture:
  track: true

60_b7_6e_2f_31_76:
  name: 60_b7_6e_2f_31_76
  mac: 60:B7:6E:2F:31:76
  icon:
  picture:
  track: true

hp4e169890:
  name: HP4E169890
  mac: B8:08:CF:D2:82:BE
  icon:
  picture:
  track: true

ekorrbo_esp:
  name: ekorrbo_esp
  mac: 48:3F:DA:59:35:D0
  icon:
  picture:
  track: true

raspberrypi:
  name: raspberrypi
  mac: B8:27:EB:DB:A6:69
  icon:
  picture:
  track: true

emmas_ipad:
  name: Emmas-iPad
  mac: 36:67:F4:52:B2:CF
  icon:
  picture:
  track: true

leas_ipad:
  name: Leas-iPad
  mac: 4E:43:B2:9D:EE:E1
  icon:
  picture:
  track: true

ekorrbo_esp_2:
  name: ekorrbo_esp
  mac: 48:3F:DA:58:4F:76
  icon:
  picture:
  track: true

emmas_ipad_2:
  name: Emmas-iPad
  mac: DE:EC:01:4B:D0:01
  icon:
  picture:
  track: true

6c_0b_84_1b_25_34:
  name: 6c_0b_84_1b_25_34
  mac: 6C:0B:84:1B:25:34
  icon:
  picture:
  track: true

ipad:
  name: iPad
  mac: 28:EC:95:7B:36:27
  icon:
  picture:
  track: true

emmas_ipad_3:
  name: Emmas-iPad
  mac: EE:8C:48:C3:1B:1A
  icon:
  picture:
  track: true

emmas_ipad_4:
  name: Emmas-iPad
  mac: 8E:63:77:9F:06:02
  icon:
  picture:
  track: true

ipad_2:
  name: iPad
  mac: FA:A9:E7:A5:CA:FE
  icon:
  picture:
  track: true

86_34_98_f9_06_16:
  name: 86_34_98_f9_06_16
  mac: 86:34:98:F9:06:16
  icon:
  picture:
  track: true

emmas_ipad_2_2:
  name: Emmas-iPad-2
  mac: EA:3C:56:1A:1B:6F
  icon:
  picture:
  track: true

leas_ipad_2:
  name: Leas-iPad
  mac: 92:6C:1B:85:B1:C8
  icon:
  picture:
  track: true

jfipadmini4:
  name: JFiPadmini4
  mac: A2:BC:4E:A8:41:20
  icon:
  picture:
  track: true

52_55_00_d1_55_01:
  name: 52_55_00_d1_55_01
  mac: 52:55:00:D1:55:01
  icon:
  picture:
  track: true

homeassistant:
  name: homeassistant
  mac: 02:11:32:2E:EE:84
  icon:
  picture:
  track: true

homeassistant_2:
  name: homeassistant
  mac: 02:11:32:25:3A:03
  icon:
  picture:
  track: true

homeassistant_3:
  name: homeassistant
  mac: 02:11:32:2D:33:D1
  icon:
  picture:
  track: true

homeassistant_4:
  name: homeassistant
  mac: 02:11:32:21:FF:32
  icon:
  picture:
  track: true

homeassistant_5:
  name: homeassistant
  mac: 02:11:32:29:AA:0F
  icon:
  picture:
  track: true

homeassistant_6:
  name: homeassistant
  mac: 02:11:32:2C:2F:19
  icon:
  picture:
  track: true

homeassistant_7:
  name: homeassistant
  mac: 02:11:32:27:53:56
  icon:
  picture:
  track: true

homeassistant_8:
  name: homeassistant
  mac: 02:11:32:21:03:26
  icon:
  picture:
  track: true

homeassistant_9:
  name: homeassistant
  mac: 02:11:32:25:35:6A
  icon:
  picture:
  track: true

homeassistant_10:
  name: homeassistant
  mac: 02:11:32:26:63:A5
  icon:
  picture:
  track: true

homeassistant_11:
  name: homeassistant
  mac: 02:11:32:28:80:7D
  icon:
  picture:
  track: true

homeassistant_12:
  name: homeassistant
  mac: 02:11:32:29:51:4E
  icon:
  picture:
  track: true

homeassistant_13:
  name: homeassistant
  mac: 02:11:32:2C:FD:A5
  icon:
  picture:
  track: true

homeassistant_14:
  name: homeassistant
  mac: 02:11:32:2E:6B:A1
  icon:
  picture:
  track: true

homeassistant_15:
  name: homeassistant
  mac: 02:11:32:23:27:0E
  icon:
  picture:
  track: true

homeassistant_16:
  name: homeassistant
  mac: 02:11:32:25:4B:97
  icon:
  picture:
  track: true

homeassistant_17:
  name: homeassistant
  mac: 02:11:32:2C:19:E7
  icon:
  picture:
  track: true

homeassistant_18:
  name: homeassistant
  mac: 02:11:32:28:B8:4A
  icon:
  picture:
  track: true

homeassistant_19:
  name: homeassistant
  mac: 02:11:32:2E:7F:FB
  icon:
  picture:
  track: true

homeassistant_20:
  name: homeassistant
  mac: 02:11:32:21:F4:87
  icon:
  picture:
  track: true

homeassistant_21:
  name: homeassistant
  mac: 02:11:32:2C:0D:75
  icon:
  picture:
  track: true

homeassistant_22:
  name: homeassistant
  mac: 02:11:32:2B:C0:26
  icon:
  picture:
  track: true

homeassistant_23:
  name: homeassistant
  mac: 02:11:32:21:A2:BA
  icon:
  picture:
  track: true

homeassistant_24:
  name: homeassistant
  mac: 02:11:32:29:D3:60
  icon:
  picture:
  track: true

homeassistant_25:
  name: homeassistant
  mac: 02:11:32:2B:26:1B
  icon:
  picture:
  track: true

f8_0f_f9_f7_27_ec:
  name: f8_0f_f9_f7_27_ec
  mac: F8:0F:F9:F7:27:EC
  icon:
  picture:
  track: true

72_41_d0_61_c7_d7:
  name: 72_41_d0_61_c7_d7
  mac: 72:41:D0:61:C7:D7
  icon:
  picture:
  track: true

homematic_raspi:
  name: homematic-raspi
  mac: 02:11:32:2F:86:83
  icon:
  picture:
  track: true

homematic_raspi_2:
  name: homematic-raspi
  mac: 02:11:32:2B:DC:F8
  icon:
  picture:
  track: true

homeassistant_26:
  name: homeassistant
  mac: 02:11:32:2B:63:4B
  icon:
  picture:
  track: true

homeassistant_27:
  name: homeassistant
  mac: 02:11:32:26:8C:01
  icon:
  picture:
  track: true

jfipadmini4_2:
  name: JFiPadmini4
  mac: 8E:BF:EE:E4:4A:DA
  icon:
  picture:
  track: true

emmas_ipad_5:
  name: Emmas-iPad
  mac: 32:37:92:95:3E:16
  icon:
  picture:
  track: true
