resources:
  - url: /local/custom-lovelace/mini-media-player-bundle.js?v=0.9.4
    type: module
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.3.3
    type: js
  - url: /local/custom-lovelace/tracker-card.js?v=0.1.5
    type: js

title: Mjövik

views:
  - title: Monitor
    icon: mdi:home
    id: home
    cards:
    - type: glance
      column_width: 25%
      show_state: false
      entities:
      - entity: switch.barnensrum
        tap_action: toggle
      - entity: switch.kok_uppe
        tap_action: toggle
      - entity: switch.koksfonster
        tap_action: toggle
      - entity: switch.sovrummet
        tap_action: toggle
      - entity: switch.stereo 
        tap_action: toggle
      - entity: light.fonster_vardagsrum
      - entity: light.glodlampan
      - entity: light.utebelysning
    - type: entities
      entities:
        - climate.mjovik
    - type: conditional
      conditions:
      - entity: binary_sensor.workday_sensor
        state: "on"
      card:
        type: entities
        entities:
        - entity: sensor.skollunch
          name: "Skollunch"
          icon: mdi:silverware-variant
    - type: glance
      entities:
      - entity: sensor.ute_temperature
        name: Ute
      - entity: sensor.daikin_outdoor
        name: Daikin
      - entity: sensor.point_home_temperature
        name: Point
      - entity: sensor.daikin_indoor
        name: Daikin
        icon: mdi:home
      - entity: sensor.vit_inne_temperature
        name: Inne 
      - entity: sensor.vit_inne_humidity
        name: Inne 
      - sensor.badtemp_tallholmen
      - entity: sensor.krypgrund_temperature
        name: Krypgrund
      - entity: sensor.krypgrund_humidity
        name: Krypgrund
      - sensor.regnmatare_rain_rate
      - binary_sensor.altandorren
    - type: iframe
      url: 'https://grafana.erlandsson.myds.me/d/A-PiyQgmk/temperatures-degc?refresh=15m&orgId=1&from=now-7d&to=now&var-temp_id=badtemp_tallholmen&var-temp_id=daikin&var-temp_id=daikin_indoor&var-temp_id=daikin_outdoor&var-temp_id=krypgrund_temperature&var-temp_id=ute_temperature&var-temp_id=vit_inne_temperature'
      aspect_ratio: 150%
  - title: Weather
    icon: mdi:weather-partlycloudy
    id: weather
    cards:
    - type: vertical-stack
      cards:
      - type: entities
        entities: 
        - sun.sun
        - sensor.dark_sky_hourly_summary
        - sensor.dark_sky_daily_summary
      - type: glance
        entities:
        - sensor.dark_sky
        - sensor.yr
        - sensor.dark_sky_temperature
        - sensor.yr_dewpoint_temperature
        - sensor.yr_precipitation
        - sensor.yr_wind_speed
        - sensor.yr_wind_direction
        - sensor.yr_cloudiness
        - sensor.yr_fog
        - sensor.yr_pressure
    - type: vertical-stack
      cards:
      - type: weather-forecast
        entity: weather.dark_sky
  - title: Energy
    icon: mdi:flash-circle
    id: energy
    cards:
    - title: Energy usage
      type: glance
      column_width: 25%
      entities:
      - entity: sensor.sparsnas_energy_consumption_momentary
        name: Total
      - sensor.iotawatt_total
      - sensor.sparsnas_iotawatt
      - entity: sensor.kwh_today
        name: Today
      - entity: sensor.kwh_current_month
        name: Monthly
    - type: iframe
      url: 'https://grafana.erlandsson.myds.me/d-solo/Sd5-ZIcmk/power-distribution?orgId=1&panelId=4&theme=light'
      aspect_ratio: 100%
  - title: Media Players
    icon: mdi:television
    id: media
    cards:
      - id: b3c591f49e044797a37008df06b68297  # Automatically created id
        type: custom:mini-media-player
        entity: media_player.lg_webos_smart_tv
        power_color: true
        show_source: true

      - id: 491ab905c8a5401e931a285b387326a1  # Automatically created id
        type: custom:mini-media-player
        entity: media_player.living_room_chromecast
        hide_power: true
        hide_volume: true
        show_progress: true

      - id: 3aa6cc7fda7647429752a94d944aea4a  # Automatically created id
        type: custom:mini-media-player
        entity: media_player.spotify
        artwork: cover
        power_color: true
        hide_volume: false
        show_progress: true
        show_source: true
      - id: 80a7e02c48614e95a96253203fbf6a18  # Automatically created id
        type: custom:upcoming-media-card
        entity: sensor.sonarr_upcoming_media
        title: Sonarr upcoming
        image_style: banner
        clock: 24
        max: 3
      - type: custom:upcoming-media-card
        entity: sensor.plex_recently_added
        title: Recently Added
        image_style: banner
        clock: 24
        date: mmdd
        icon: none

  - title: Automation
    icon: mdi:home-automation
    id: auto
    cards:
    - title: Automation
      type: glance
      column_width: 30%
      entities:
      - entity:  script.goodnight
        name: Godnatt
        tap_action: toggle
        show_state: false
      - entity:  input_boolean.auto_ac
        name: Auto AC
        show_state: false
      - input_boolean.vacation_mode
      - input_boolean.trip_mode
      - entity: input_number.trip_temp_high
        name: "Turné max temp"
      - entity: input_number.trip_temp_low
        name: "Turné min temp"
    - title: Internet traffic
      type: glance
      column_width: 25%
      entities:
      - entity: sensor.snmp_wan_in
      - entity: sensor.snmp_wan_out
      - entity: sensor.snmp_lan_in
      - entity: sensor.snmp_lan_out

