resources:
  - url: /local/custom-lovelace/mini-media-player-bundle.js?v=0.9.5
    type: module
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.3.3
    type: js
  - url: /local/custom-lovelace/tracker-card.js?v=0.1.5
    type: js
  - url: /local/custom-lovelace/time-input-row.js?v=f503b7
    type: js
  - url: /local/custom-lovelace/weather-card.js?v=0
    type: js
  - url: /local/custom-lovelace/simple-thermostat.js?v=2
    type: module
  # - url: /local/custom-lovelace/mini-graph-card-bundle.js?v=0.0.8
  #  type: js

title: Mjövik

views:
  - title: Monitor
    icon: mdi:home
    id: home
    cards:
      - type: glance
        id: 9a1d672019d445a5b3405f2d3ea32613  # Automatically created id
        column_width: 25%
        show_state: false
        entities:
          - entity: switch.barnensrum
            tap_action: toggle
            hold_action: more-info
          - entity: switch.kok_uppe
            tap_action: toggle
            hold_action: more-info
          - entity: switch.koksfonster
            tap_action: toggle
            hold_action: more-info
          - entity: switch.sovrummet
            tap_action: toggle
            hold_action: more-info
          - entity: switch.stjarnor
            icon: mdi:star-outline
            tap_action: toggle
            hold_action: more-info
          - entity: switch.julgranen
            tap_action: toggle
            hold_action: more-info
          - entity: switch.ljusslingor
            tap_action: toggle
            hold_action: more-info
            icon: mdi:road-variant
          - entity: switch.altanen
            tap_action: toggle
            hold_action: more-info
            icon: mdi:lightbulb
          - entity: light.fonster_vardagsrum
            tap_action: toggle
            hold_action: more-info
          - entity: light.glodlampan
            tap_action: toggle
            hold_action: more-info
          - entity: light.utebelysning
            icon: mdi:wall-sconce-variant
            tap_action: toggle
            hold_action: more-info
        title: Lampor
        columns: 4
        theme: Backend-selected
      - id: febc87877dd446d9b88f75ee439939f8  # Automatically created id
        type: entities
        entities:
          - climate.mjovik
      - id: 95c053757e9c4c8497a06217b41d9ad5  # Automatically created id
        type: custom:simple-thermostat
        entity: climate.mjovik
        step_size: 1
        hide:
          state: true
          temperature: true
        sensors:
          - entity: sensor.vit_inne_temperature
            name: Temperatur (vit)
          - entity: sensor.iotawatt_inverter
            name: Effekt
          - entity: sensor.inverter_kwh
            name: Senaste 24h

      - id: 8d16e9c90406446794f17c2fe1d747e3  # Automatically created id
        type: conditional
        conditions:
          - entity: binary_sensor.workday_sensor
            state: on
        card:
          type: entities
          entities:
            - entity: sensor.skollunch
              name: Skollunch
              icon: mdi:silverware-variant
      - id: deb971d9ca014e93abf0255ea35f261f  # Automatically created id
        type: glance
        title: Klimat
        entities:
          - entity: sensor.ute_temperature
            name: Ute
          - entity: sensor.daikin_outdoor
            name: Daikin
          - entity: sensor.point_home_temperature
            name: Point
          - entity: sensor.daikin_indoor
            name: Daikin
            icon: mdi:home
          - entity: sensor.vit_inne_temperature
            name: Inne
          - entity: sensor.vit_inne_humidity
            name: Inne
          # - sensor.badtemp_tallholmen
          - entity: sensor.krypgrund_temperature
            name: Krypgrund
          - entity: sensor.krypgrund_humidity
            name: Krypgrund
          - sensor.regnmatare_rain_rate
          # - binary_sensor.altandorren
      - id: 7a4ec3a0d8e14f2d99cad47027b3d63e  # Automatically created id
        type: iframe
        url: https://grafana.erlandsson.myds.me/d/A-PiyQgmk/temperatures-degc?refresh=5m&orgId=1&from=now-7d&to=now&var-temp_id=badtemp_tallholmen&var-temp_id=daikin&var-temp_id=daikin_indoor&var-temp_id=daikin_outdoor&var-temp_id=krypgrund_temperature&var-temp_id=ute_temperature&var-temp_id=vit_inne_temperature&var-temp_id=point_home_temperature&kiosk=tv
        aspect_ratio: 150%
  - title: Weather
    icon: mdi:weather-partlycloudy
    id: weather
    cards:
      - id: 27da5b601d164790bd7e060f72ce86f2  # Automatically created id
        type: vertical-stack
        cards:
          - type: entities
            entities:
              - sun.sun
              - sensor.dark_sky_hourly_summary
              - sensor.dark_sky_daily_summary
          - type: glance
            entities:
              - sensor.dark_sky
              - sensor.yr
              - sensor.dark_sky_temperature
              - sensor.yr_dewpoint_temperature
              - sensor.yr_precipitation
              - sensor.yr_wind_speed
              - sensor.yr_wind_direction
              - sensor.yr_cloudiness
              - sensor.yr_fog
              - sensor.yr_pressure
      - id: 9bba718397a445e58517d5ca1e7d242c  # Automatically created id
        type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
            title: Dark Sky
          - type: weather-forecast
            entity: weather.smhi_home
            title: SMHI
      - id: 9bba718397a445e58517d5ca1e7d242d  # Automatically created id
        type: vertical-stack
        cards:
          - type: custom:weather-card
            title: Dark Sky
            entity_weather: weather.dark_sky
            entity_sun: sun.sun
          - type: custom:weather-card
            title: SMHI
            entity_weather: weather.smhi_home
            entity_sun: sun.sun
  - title: Energy
    icon: mdi:flash-circle
    id: energy
    cards:
      - id: 5d6bfe91e2a64b4da1c0c5380d181429  # Automatically created id
        title: Energy usage
        type: glance
        column_width: 25%
        entities:
          - entity: sensor.sparsnas_energy_consumption_momentary
            name: Total
          - entity: sensor.iotawatt_total
            name: IoTaWatt
          - entity: sensor.sparsnas_iotawatt
            name: Others
          - entity: sensor.kwh_today
            name: Today
      - id: 5a2998cfc0c646c995e417e3ba4e469e  # Automatically created id
        type: iframe
        url: https://grafana.erlandsson.myds.me/d-solo/Sd5-ZIcmk/power-distribution?orgId=1&panelId=4&theme=light&from=now/d&to=now&refresh=10m
        aspect_ratio: 100%
      - id: fda38f0d67ad420d917ca4def67e16fe  # Automatically created id
        type: iframe
        url: https://grafana.erlandsson.myds.me/d/Sd5-ZIcmk/power-distribution?orgId=1&var-kwh_to_sek=1.41&kiosk=tv
        aspect_ratio: 105%
  - title: Media Players
    icon: mdi:television
    id: media
    cards:
      - id: c454454d3ca24ff48139382428d87710  # Automatically created id
        type: entity-filter
        state_filter:
          - on
          - off
          - playing
          - paused
          - idle
        entities:
          - id: b3c591f49e044797a37008df06b68297  # Automatically created id
            type: custom:mini-media-player
            entity: media_player.lg_webos_smart_tv
            power_color: true
            show_source: small
            group: true
            name: TV
            artwork: none
            icon: mdi:television

          - type: custom:mini-media-player
            entity: media_player.lg_43uh664vzc
            hide_power: true
            hide_volume: true
            show_progress: true
            hide_controls: true
          - type: custom:mini-media-player
            entity: media_player.living_room_chromecast
            hide_power: true
            hide_volume: true
            show_progress: true
      - id: 3aa6cc7fda7647429752a94d944aea4a  # Automatically created id
        type: custom:mini-media-player
        entity: media_player.spotify
        artwork: full-cover
        hide_power: true
        power_color: true
        hide_volume: false
        show_progress: true
        show_source: small

      - id: 80a7e02c48614e95a96253203fbf6a18  # Automatically created id
        type: custom:upcoming-media-card
        entity: sensor.sonarr_upcoming_media
        title: Sonarr upcoming
        image_style: banner
        clock: 24
        max: 3
      - id: 8907d70b6d904063b04dbd41444e2967  # Automatically created id
        type: custom:upcoming-media-card
        entity: sensor.plex_recently_added
        title: Recently Added
        image_style: banner
        clock: 24
        date: mmdd
        icon: none

  - title: Automation
    icon: mdi:home-automation
    id: auto
    cards:
      - id: 7d90773516234108b7f1d9eeb4dccab5  # Automatically created id
        title: Automation
        type: glance
        columns: 4
        entities:
          - entity: script.goodnight
            name: Godnatt
            tap_action: toggle
            hold_action: more-info
          - entity: input_boolean.auto_ac
            name: Auto AC
            tap_action: toggle
            hold_action: more-info
          - entity: input_boolean.vacation_mode
            tap_action: toggle
            hold_action: more-info
          - entity: input_boolean.trip_mode
            tap_action: toggle
            hold_action: more-info
      - id: 2ccc5e391d26426987c96438b5be24fb  # Automatically created id
        type: conditional
        conditions:
          - entity: input_boolean.trip_mode
            state: on
        card:
          type: entities
          entities:
            - entity: input_number.trip_temp_high
              name: Turné max temp
            - entity: input_number.trip_temp_low
              name: Turné min temp
      - id: 12a9736b7feb4cec86db24d3cc06f7d4  # Automatically created id
        type: thermostat
        entity: climate.mjovik
      - id: c7438f76e458446e91072774841fa6c5  # Automatically created id
        title: Internet traffic
        type: glance
        entities:
          - entity: sensor.asuswrt_download_speed
          - entity: sensor.asuswrt_upload_speed
      - id: 434d7c830ffd44eb9c8c94fcafc26e09  # Automatically created id
        type: vertical-stack
        cards:
          - type: sensor
          # entity: sensor.rtac68u_mbps_in
            entity: sensor.asuswrt_download_speed
            accuracy: 24
          - type: sensor
          # entity: sensor.rtac68u_mbps_out
            entity: sensor.asuswrt_upload_speed
            accuracy: 24
      - id: 247bd46dc3df49dda8fd1c6b7f6ec256  # Automatically created id
        type: sensor
        entity: sensor.rtac68u_kbytesec_received
        accuracy: 24
      - id: 31bf95f32cc64a08a31d006aa4d81bdc  # Automatically created id
        type: sensor
        entity: sensor.rtac68u_kbytesec_sent
        accuracy: 24
      - id: a24510066b6c4436aa2c665e7662de7e  # Automatically created id
        type: custom:tracker-card
        title:
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
