sensor:
  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_api_key
    host: 192.168.1.2
    port: 8989
    days: 60
  - platform: plex_recently_added
    token: !secret plex_token
    host: 192.168.1.2
    port: 32400
    download_images: true
    max: 5
    section_types:
    - movie
    - show

