homeassistant:
  customize:
    sensor.iotawatt_total:
      friendly_name: IoTaWatt
    sensor.sparsnas_energy_consumption_momentary:
      icon: mdi:flash-circle
      friendly_name: "Energy total"
    sensor.iotawatt_total:
      icon: mdi:flash-circle
      friendly_name: IoTaWatt
    sensor.sparsnas_iotawatt:
      icon: mdi:flash-circle
    sensor.sparsnas_energy_consumption_momentary:
      friendly_name: Energy total
    sensor.iotawatt_inverter:
      friendly_name: Inverter
      icon: mdi:flash-circle
    sensor.inverter_kwh:
      icon: mdi:flash-circle
    sensor.kwh_today:
      friendly_name: Today total
    sensor.inverter_daily:
      friendly_name: Inverter Today
    sensor.sparsnas_daily:
      friendly_name: Sparsnas Today
    sensor.sparsnas_monthly:
      friendly_name: Sparsnas this month
    sensor.sparsnas_yearly:
      friendly_name: Sparsnas this year

sensor:
#IoTaWatt config
  - platform: influxdb
    host: 192.168.1.2
    queries:
      - name: Iotawatt Total (old)
        unit_of_measurement: W
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"entity_id" = ''Total'''
        measurement: '"Watts"'
        field: value
        database: iotawatt
      - name: Iotawatt inverter (old)
        unit_of_measurement: W
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"entity_id" = ''Inverter'''
        measurement: '"Watts"'
        field: value
        database: iotawatt
  - platform: template
    sensors:
      sparsnas_iotawatt:
        friendly_name: "Others"
        unit_of_measurement: W
        value_template: >-
          {% set value = (states("sensor.sparsnas_energy_consumption_momentary") | float -  (states("sensor.iotawatt") | float)) | round(1) %}
          {% if value < 0 %}
          {{ states("sensor.sparsnas_iotawatt") }}
          {% else %}
          {{ value }}
          {% endif %}
  - platform: rest
    resource: 'http://192.168.1.22/status?outputs=yes&inputs=yes'
    name: iotawatt
    value_template: '{{ value_json.outputs[2].value | float | round(1) }}'
    unit_of_measurement: "W"
    json_attributes:
      - outputs
      - inputs
  - platform: template
    sensors:
      iotawatt_appliences:
        value_template: '{{ states.sensor.iotawatt.attributes.outputs[0].value }}'
        friendly_name_template: '{{ states.sensor.iotawatt.attributes.outputs[0].name }}'
        unit_of_measurement: "W"
      iotawatt_inverter:
        value_template: '{{ states.sensor.iotawatt.attributes.outputs[1].value | round(1) }}'
        friendly_name_template: '{{ states.sensor.iotawatt.attributes.outputs[1].name }}'
        unit_of_measurement: "W"
      iotawatt_total:
        value_template: '{{ states.sensor.iotawatt.attributes.outputs[2].value | round(1) }}'
        friendly_name_template: '{{ states.sensor.iotawatt.attributes.outputs[2].name }}'
        unit_of_measurement: "W"
      dishwasher_runtime:
        device_class: timestamp
        value_template: >
          {% if is_state('sensor.washer_runtime', None)  and
          state_attr('sensor.iotawatt', 'inputs')[9].Watts|float > 3 %}
            {{ now() }}
          {% else %}
            {{ None }}
          {% endif %}
      washer_runtime:
        device_class: timestamp
        value_template: >
          {% if is_state('sensor.washer_runtime', '')  and
          state_attr('sensor.iotawatt', 'inputs')[1].Watts|float > 3 %}
            {{ now() }}
          {% else %}
            {{''}}
          {% endif %}
  - platform: integration
    source: sensor.iotawatt_inverter
    name: Inverter kWh
    unit_prefix: k
    round: 2
          

automation:
- id: 'sparsnas_setup'
  alias: Sparsnäs setup
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      payload: '{"device": {"sw_version": "215a4aa", "name": "Sparsnäs 602064", "identifiers":
        "602064", "model": "Sparsnäs", "manufacturer": "IKEA"}, "unit_of_measurement":
        "kWh", "json_attributes": ["Sequence", "FreqErr", "Effect", "Data4", "Sensor",
        "battery"], "name": "Sparsnäs kWh", "unique_id": "sparsnas_602064_kwh", "state_topic":
        "sparsnas/602064", "value_template": "{{ value_json.kWh | round(2) }}", "icon":
        "mdi:flash-circle"}'
      topic: home/sensor/sparsnas/602064_kwh/config
    service: mqtt.publish
  - data:
      payload: '{"device": {"sw_version": "215a4aa", "name": "Sparsnäs 602064", "identifiers":
        "602064", "model": "Sparsnäs", "manufacturer": "IKEA"}, "unit_of_measurement":
        "W", "json_attributes": ["Sequence", "FreqErr","Effect", "Data4", "Sensor",
        "battery"], "name": "Sparsnäs Watt", "unique_id": "sparsnas_602064_watt",
        "state_topic": "sparsnas/602064", "value_template": "{{ value_json.Watt |
        round(1) }}", "icon": "mdi:flash-circle"}'
      topic: home/sensor/sparsnas/602064_Watt/config
    service: mqtt.publish

utility_meter:
  sparsnas_yearly:
    source: sensor.sparsnas_energy_consumption_over_time 
    cycle: yearly
  sparsnas_monthly:
    source: sensor.sparsnas_energy_consumption_over_time
    cycle: monthly
  sparsnas_daily:
    source: sensor.sparsnas_energy_consumption_over_time
    cycle: daily
  inverter_daily:
    source: sensor.inverter_kwh
    cycle: daily

