homeassistant:
  customize:
    sensor.snmp_wan_in:
      friendly_name: 'WAN Download'
      icon: mdi:download
    sensor.snmp_wan_out:
      friendly_name: 'WAN Upload'
      icon: mdi:upload
    sensor.snmp_lan_in:
      friendly_name: 'LAN Download'
      icon: mdi:download
    sensor.snmp_lan_out:
      friendly_name: 'LAN Upload'
      icon: mdi:upload
sensor:
  - platform: template
    sensors: 
        rtac68u_mbitsec_sent:
          value_template: "{{ (states('sensor.rtac68u_kbytesec_sent')|float * 0.008)|round(2) }}"
          unit_of_measurement: "Mbit/sec"
          friendly_name: "RT-AC68U sent"
          icon_template: mdi:upload-network
        rtac68u_mbitsec_received:
          value_template: "{{ (states('sensor.rtac68u_kbytesec_received')|float * 0.008)|round(2) }}"
          unit_of_measurement: "Mbit/sec"
          friendly_name: "RT-AC68U received"
          icon_template: mdi:download-network
  - platform: influxdb
    host: 192.168.1.2
    queries:
        # SELECT derivative(("ifHCInOctets"), 1s)*-8 FROM "snmp" WHERE "ifName" = 'eth0' GROUP BY "ifName" ORDER BY time DESC LIMIT 1;
      - name: snmp_wan_in
        unit_of_measurement: Mbps
        value_template: '{{ value | round(2) }}'
        group_function: '-0.000008*'
        where: "ifName = 'eth0' ORDER BY time DESC LIMIT 1" 
        measurement: snmp
        field: derivative(ifHCInOctets, 1s)
        database: telegraf
      - name: snmp_wan_out
        unit_of_measurement: Mbps
        value_template: '{{ value | round(2) }}'
        group_function: '-0.000008*'
        where: "ifName = 'eth0' ORDER BY time DESC LIMIT 1" 
        measurement: snmp
        field: derivative(ifHCOutOctets, 1s)
        database: telegraf
      - name: snmp_lan_in
        unit_of_measurement: Mbps
        value_template: '{{ value | round(2) }}'
        group_function: '-0.000008*'
        where: "ifName = 'br0' ORDER BY time DESC LIMIT 1" 
        measurement: snmp
        field: derivative(ifHCInOctets, 1s)
        database: telegraf
      - name: snmp_lan_out
        unit_of_measurement: Mbps
        value_template: '{{ value | round(2) }}'
        group_function: '-0.000008*'
        where: "ifName = 'br0' ORDER BY time DESC LIMIT 1" 
        measurement: snmp
        field: derivative(ifHCOutOctets, 1s)
        database: telegraf
