homeassistant:
  customize:
    sensor.badtemp_tallholmen:
      icon: mdi:swim
    sensor.pressure:
      icon: mdi:gauge
    sensor.dark_sky_temperature:
      extra_data_template: '${"Feels like: " + entities["sensor.dark_sky_apparent_temperature"].state
        + "°C,  " + "Humidity: " + entities["sensor.dark_sky_humidity"].state + "% ("
        + entities["sensor.dark_sky_dew_point"].state +"°C)"}'
      hidden: true
    sensor.dark_sky_wind_speed:
      extra_data_template: ${entities['sensor.dark_sky_wind_bearing'].state + "°"}
    sensor.ute_temperature:
      extra_data_template: '${ entities["sensor.daikin_outdoor"].state == "unknown" ?
        "" : "Daikin: " + entities["sensor.daikin_outdoor"].state + "°C"}'
      friendly_name: Ute Temperatur
    sensor.dark_sky:
      extra_data_template: '${"Feels like: " + entities["sensor.dark_sky_apparent_temperature"].state
        + "°C,  " + "Humidity: " + entities["sensor.dark_sky_humidity"].state + "% ("
        + entities["sensor.dark_sky_dew_point"].state +"°C)"}'

# Weather prediction
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

sensor:
  - platform: darksky #https://pastebin.com/iX7u4ZSg
    api_key: !secret darksky_api_key
    name: dark_sky_forecast
    scan_interval:
      hours: 1
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
    monitored_conditions:
      - icon
      - precip_probability
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - precip_probability
      - precip_intensity
  - platform: darksky #https://pastebin.com/iX7u4ZSg
    api_key: !secret darksky_api_key
    scan_interval: '00:05'
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - temperature
      - apparent_temperature
      - precip_probability
      - wind_speed
      - pressure
      - wind_bearing
      - humidity
      - cloud_cover
      - dew_point
      - hourly_summary
      - daily_summary
  # - platform: rest
  #   resource: https://api.ioe.allbin.se/buoys
  #   name: Badtemp Tallholmen
  #   unit_of_measurement: °C
  #   value_template: '{{ value_json|selectattr("name", "equalto", "Tallholmen")|map(attribute="temperature")|first|round(1) }}'
  - platform: template
    sensors:
      dark_sky_fc:
        value_template: >-
          {% set dow = {
           0: "Mon",
           1: "Tis",
           2: "Ons",
           3: "Tor",
           4: "Fre",
           5: "Lör",
           6: "Sön"
          } %}
          {% set weather = {
            "clear-day": "mdi:weather-sunny",
            "clear-night": "mdi:weather-night",
            "cloudy": "mdi:weather-cloudy",
            "rain": "mdi:weather-pouring",
            "sleet": "mdi:weather-snowy-rainy",
            "snow": "mdi:weather-snowy",
            "wind": "mdi:weather-windy",
            "fog": "mdi:weather-fog",
            "partly-cloudy-day": "mdi:weather-partly-cloudy",
            "partly-cloudy-night": "mdi:weather-night-partly-cloudy"
          } %}
          {% set base = 'sensor.dark_sky_forecast_' %}
          {%- for i in [ 1, 2, 3, 4] -%}
            {{ dow[now().isoweekday() + i - 1]  }}:
            {{- weather[states('{}icon_{}d'.format(base, i))] -}}:
            {{- states('{}daytime_high_temperature_{}d'.format(base, i)) -}}°:
            {{- states('{}precip_probability_{}d'.format(base, i)) -}}%
            {%- if not loop.last %}:{% endif %}
          {%- endfor %}
      dark_sky:
        entity_picture_template: "{{states.sensor.dark_sky_summary.attributes.entity_picture}}"
        value_template: "{{states('sensor.dark_sky_temperature')}}"
        friendly_name: "Dark Sky"
        friendly_name_template: "{{states.sensor.dark_sky_summary.state}} — ⟨Dark Sky⟩"
        unit_of_measurement: "°C"
        device_class: temperature
        # entity_picture_template: >-
        #   {% if is_state('sun.sun', 'above_horizon') %}
        #   //api.met.no/weatherapi/weathericon/1.1/?symbol={{states.sensor.yr_symbol.state}};is_night=0;content_type=image/svg%2Bxml
        #   {% else %}
        #   //api.met.no/weatherapi/weathericon/1.1/?symbol={{states.sensor.yr_symbol.state}};is_night=1;content_type=image/svg%2Bxml
        #   {% endif %}
      pressure:
        value_template: "{{  (float(states.sensor.dark_sky_pressure.state) + float(states.sensor.dark_sky_pressure.state))/2|round(2) }}"
        unit_of_measurement: hPa
