homeassistant:
  customize:
    sensor.yr_symbol:
      hidden: true
    sensor.yr_wind_speed:
      extra_data_template: ${entities['sensor.yr_wind_direction'].state + "°"}
      icon: mdi:weather-windy-variant
    sensor.yr_wind_direction:
      hidden: true
      icon: mdi:weather-windy
    sensor.yr_precipitation:
      icon: mdi:weather-pouring
    sensor.yr_fog:
      icon: mdi:weather-fog
    sensor.yr_cloudiness:
      extra_data_template: '${"H: " + entities[''sensor.yr_high_clouds''].state + "%,
        M: " + entities[''sensor.yr_medium_clouds''].state +"%, L: " + entities[''sensor.yr_low_clouds''].state
        + "%"}'
      icon: mdi:weather-cloudy
    sensor.yr_high_clouds:
      hidden: true
      icon: mdi:weather-cloudy
    sensor.yr_medium_clouds:
      hidden: true
      icon: mdi:weather-cloudy
    sensor.yr_low_clouds:
      hidden: true
      icon: mdi:weather-cloudy
    sensor.yr_dewpoint_temperature:
      hidden: true
      icon: mdi:thermometer-lines
    sensor.yr_humidity:
      hidden: true
      icon: mdi:water-percent
    sensor.yr_pressure:
      icon: mdi:gauge
    sensor.yr_temperature:
      hidden: true
      extra_data_template: '${"Humidity: " + entities[''sensor.yr_humidity''].state +
        "% (" + entities[''sensor.yr_dewpoint_temperature''].state +"°C)"}'
      icon: mdi:thermometer
    sensor.yr:
      extra_data_template: '${"Humidity: " + entities[''sensor.yr_humidity''].state +
        "% (" + entities[''sensor.yr_dewpoint_temperature''].state +"°C)"}'
    sensor.pressure:
      icon: mdi:gauge

# Weather prediction
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
  - platform: template
    sensors:
      yr:
        value_template: "{{states.sensor.yr_temperature.state}}"
        friendly_name: 'Yr - Väder'
        unit_of_measurement: "°C"
        friendly_name_template: >-
          {% if states.sensor.yr_symbol.state | int==1%}Klart
          {% elif states.sensor.yr_symbol.state | int==2%}Lätt monlighet
          {% elif states.sensor.yr_symbol.state | int==3%}Halvklart till mulet
          {% elif states.sensor.yr_symbol.state | int==4%}Moln
          {% elif states.sensor.yr_symbol.state | int==5%}Sol med inslag skurar
          {% elif states.sensor.yr_symbol.state | int==6%}Sol med inslag av åska och skurar
          {% elif states.sensor.yr_symbol.state | int==7%}Sol med inslag av snöblandat regn
          {% elif states.sensor.yr_symbol.state | int==8%}Sol med inslag av snö
          {% elif states.sensor.yr_symbol.state | int==9%}Duggregn
          {% elif states.sensor.yr_symbol.state | int==10%}Regn
          {% elif states.sensor.yr_symbol.state | int==11%}Regn och åska
          {% elif states.sensor.yr_symbol.state | int==12%}Snöblandat regn
          {% elif states.sensor.yr_symbol.state | int==13%}Snö
          {% elif states.sensor.yr_symbol.state | int==14%}SnowThunder
          {% elif states.sensor.yr_symbol.state | int==15%}Dimma
          {% elif states.sensor.yr_symbol.state | int==16%}Titta ut!
          {% elif states.sensor.yr_symbol.state | int==17%}Titta ut!
          {% elif states.sensor.yr_symbol.state | int==18%}Titta ut!
          {% elif states.sensor.yr_symbol.state | int==19%}Titta ut!
          {% elif states.sensor.yr_symbol.state | int==20%}Snöblandat regn och åska
          {% elif states.sensor.yr_symbol.state | int==21%}Sol och snö med inslag av åska
          {% elif states.sensor.yr_symbol.state | int==22%}Lätt regn
          {% elif states.sensor.yr_symbol.state | int==23%}SleetThunder
          {% elif states.sensor.yr_symbol.state | int==24%}DrizzleThunderSun
          {% elif states.sensor.yr_symbol.state | int==25%}RainThunderSun
          {% elif states.sensor.yr_symbol.state | int==26%}LightSleetThunderSun
          {% elif states.sensor.yr_symbol.state | int==27%}HeavySleetThunderSun
          {% elif states.sensor.yr_symbol.state | int==28%}LightSnowThunderSun
          {% elif states.sensor.yr_symbol.state | int==29%}HeavySnowThunderSun
          {% elif states.sensor.yr_symbol.state | int==30%}DrizzleThunder
          {% elif states.sensor.yr_symbol.state | int==31%}LightSleetThunder
          {% elif states.sensor.yr_symbol.state | int==32%}HeavySleetThunder
          {% elif states.sensor.yr_symbol.state | int==33%}LightSnowThunder
          {% elif states.sensor.yr_symbol.state | int==34%}HeavySnowThunder
          {% elif states.sensor.yr_symbol.state | int==35%}Titta ut!
          {% elif states.sensor.yr_symbol.state | int==36%}Titta ut!
          {% elif states.sensor.yr_symbol.state | int==37%}Titta ut!
          {% elif states.sensor.yr_symbol.state | int==38%}Titta ut!
          {% elif states.sensor.yr_symbol.state | int==39%}Titta ut!
          {% elif states.sensor.yr_symbol.state | int==40%}DrizzleSun
          {% elif states.sensor.yr_symbol.state | int==41%}Regnskurar
          {% elif states.sensor.yr_symbol.state | int==42%}LightSleetSun
          {% elif states.sensor.yr_symbol.state | int==43%}HeavySleetSun
          {% elif states.sensor.yr_symbol.state | int==44%}LightSnowSun
          {% elif states.sensor.yr_symbol.state | int==45%}HeavysnowSun
          {% elif states.sensor.yr_symbol.state | int==46%}Duggregn
          {% elif states.sensor.yr_symbol.state | int==47%}Lätt snöblandat regn
          {% elif states.sensor.yr_symbol.state | int==48%}Kraftigt snöblandat regn
          {% elif states.sensor.yr_symbol.state | int==49%}Lätt snöfall
          {% elif states.sensor.yr_symbol.state | int==50%}Kraftigt snöfall
          {% endif %}
          — ⟨Yr⟩
        entity_picture_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
          //api.met.no/weatherapi/weathericon/1.1/?symbol={{states.sensor.yr_symbol.state}};is_night=0;content_type=image/svg%2Bxml
          {% else %}
          //api.met.no/weatherapi/weathericon/1.1/?symbol={{states.sensor.yr_symbol.state}};is_night=1;content_type=image/svg%2Bxml
          {% endif %}
      pressure:
        value_template: "{{  (float(states.sensor.yr_pressure.state) + float(states.sensor.dark_sky_pressure.state))/2|round(2) }}"
        unit_of_measurement: hPa
